"""
bus/event_bus.py — In-process pub/sub event bus for the swarm.

Replaces the polling model with true event-driven delivery.
Agents subscribe to named event types; when any agent publishes an event
all matching subscribers are notified — synchronously for CRITICAL events,
in background daemon threads for everything else.

No external dependencies: standard-library threading only.
"""

import threading
import time
import uuid
from collections import defaultdict


# ---------------------------------------------------------------------------
# Canonical event-type registry
# ---------------------------------------------------------------------------

SWARM_EVENTS: dict[str, str] = {
    # Sensor layer
    "sensor.reading":      "New sensor data received",
    "sensor.anomaly":      "Anomaly detected in sensor data",
    # Node lifecycle
    "node.joined":         "New node joined the swarm",
    "node.left":           "Node left or disconnected",
    "node.dead":           "Node declared dead by health monitor",
    # Task lifecycle
    "task.assigned":       "ML task assigned to a node",
    "task.completed":      "ML task completed with result",
    "task.failed":         "ML task failed or timed out",
    "task.reassigned":     "Task reassigned from dead node",
    # Pipeline
    "pipeline.triggered":  "ML pipeline cycle started",
    "pipeline.completed":  "ML pipeline cycle finished",
    # Action layer
    "action.alert":        "Alert generated by action agent",
    "action.workorder":    "Work order created",
    "action.emergency":    "Emergency escalation triggered",
    # Infrastructure
    "db.synced":           "Database sync completed with peer",
    # Security
    "security.challenge":  "Authentication challenge sent",
    "security.verified":   "Node authentication successful",
    "security.rejected":   "Rogue node rejected",
}


# ---------------------------------------------------------------------------
# EventBus
# ---------------------------------------------------------------------------

class EventBus:
    """
    Thread-safe, in-process publish/subscribe bus.

    Subscribers register a callable and an optional agent_id.
    Publishers call publish() with an event type and a data dict.

    Delivery rules:
      - priority == "CRITICAL" → synchronous, caller blocks until all done
      - all others             → each subscriber gets a daemon thread
      - subscriptions to "*"  → receive every event type
    """

    def __init__(self):
        self._subscribers: dict[str, list] = defaultdict(list)
        self._event_log:   list            = []
        self._max_log:     int             = 1000
        self._lock         = threading.Lock()

    # ------------------------------------------------------------------
    # Subscription management
    # ------------------------------------------------------------------

    def subscribe(
        self,
        event_type: str,
        callback,
        agent_id: str = None,
    ) -> None:
        """
        Register *callback* to be invoked whenever *event_type* is published.

        Use event_type="*" to subscribe to all events.
        *agent_id* is used for logging and targeted unsubscribe.
        """
        aid = agent_id or str(uuid.uuid4())[:8]
        with self._lock:
            self._subscribers[event_type].append({
                "callback":      callback,
                "agent_id":      aid,
                "subscribed_at": time.time(),
            })
        print(f"[EVENT] {aid} subscribed to '{event_type}'")

    def unsubscribe(self, event_type: str, agent_id: str) -> None:
        with self._lock:
            self._subscribers[event_type] = [
                s for s in self._subscribers[event_type]
                if s["agent_id"] != agent_id
            ]

    # ------------------------------------------------------------------
    # Publishing
    # ------------------------------------------------------------------

    def publish(
        self,
        event_type: str,
        data:       dict,
        sender_id:  str  = "system",
        priority:   str  = "MEDIUM",
    ) -> None:
        """
        Publish *data* under *event_type*.

        CRITICAL events are delivered synchronously (blocking).
        All others are delivered in daemon threads so publishing never blocks.
        """
        event = {
            "event_id":    str(uuid.uuid4()),
            "event_type":  event_type,
            "data":        data,
            "sender_id":   sender_id,
            "priority":    priority,
            "timestamp":   time.time(),
            "delivered_to": [],
        }

        with self._lock:
            self._event_log.append(event)
            if len(self._event_log) > self._max_log:
                self._event_log = self._event_log[-self._max_log:]
            # Snapshot subscriber lists under the lock to avoid races
            named    = list(self._subscribers.get(event_type, []))
            wildcard = list(self._subscribers.get("*", []))

        for sub in named + wildcard:
            try:
                if priority == "CRITICAL":
                    # Synchronous — guarantees delivery before publish() returns
                    sub["callback"](event)
                else:
                    threading.Thread(
                        target=sub["callback"],
                        args=(event,),
                        daemon=True,
                        name=f"event-{event_type}-{sub['agent_id']}",
                    ).start()
                event["delivered_to"].append(sub["agent_id"])
            except Exception as exc:
                print(f"[EVENT] Delivery error to {sub['agent_id']}: {exc}")

    # ------------------------------------------------------------------
    # Query / inspection
    # ------------------------------------------------------------------

    def get_events(
        self,
        event_type: str   = None,
        since:      float = 0,
        limit:      int   = 50,
    ) -> list:
        with self._lock:
            events = list(self._event_log)
        if event_type:
            events = [e for e in events if e["event_type"] == event_type]
        if since > 0:
            events = [e for e in events if e["timestamp"] > since]
        events.sort(key=lambda e: e["timestamp"], reverse=True)
        return events[:limit]

    def get_stats(self) -> dict:
        with self._lock:
            now = time.time()
            return {
                "total_events":     len(self._event_log),
                "event_types":      list(self._subscribers.keys()),
                "subscriber_count": sum(
                    len(v) for v in self._subscribers.values()
                ),
                "recent_events":    sum(
                    1 for e in self._event_log
                    if now - e["timestamp"] < 60
                ),
            }


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

_event_bus = EventBus()


def get_event_bus() -> EventBus:
    """Return the process-wide EventBus singleton."""
    return _event_bus
